### ISSUE TITLE
GetByName no longer works for resources with more than 1 space in the name

### ISSUE THREAD

**Issue by bpedman** [zscaler/zscaler-sdk-go#169]
### Confirmation

- [X] My issue isn't already found on the issue tracker.
- [X] I have replicated my issue using the latest version of the library and it is still present.

### zscaler-sdk-go version

v2.1.1

### Go environment

GO111MODULE=''
GOARCH='arm64'
GOBIN=''
GOCACHE='/Users/bpedersen/Library/Caches/go-build'
GOENV='/Users/bpedersen/Library/Application Support/go/env'
GOEXE=''
GOEXPERIMENT=''
GOFLAGS=''
GOHOSTARCH='arm64'
GOHOSTOS='darwin'
GOINSECURE=''
GOMODCACHE='/Users/bpedersen/go/pkg/mod'
GONOPROXY=''
GONOSUMDB=''
GOOS='darwin'
GOPATH='/Users/bpedersen/go'
GOPRIVATE=''
GOPROXY='https://proxy.golang.org,direct'
GOROOT='/opt/homebrew/Cellar/go/1.21.1/libexec'
GOSUMDB='sum.golang.org'
GOTMPDIR=''
GOTOOLCHAIN='auto'
GOTOOLDIR='/opt/homebrew/Cellar/go/1.21.1/libexec/pkg/tool/darwin_arm64'
GOVCS=''
GOVERSION='go1.21.1'
GCCGO='gccgo'
AR='ar'
CC='cc'
CXX='c++'
CGO_ENABLED='1'
GOMOD='/dev/null'
GOWORK=''
CGO_CFLAGS='-O2 -g'
CGO_CPPFLAGS=''
CGO_CXXFLAGS='-O2 -g'
CGO_FFLAGS='-O2 -g'
CGO_LDFLAGS='-O2 -g'
PKG_CONFIG='pkg-config'
GOGCCFLAGS='-fPIC -arch arm64 -pthread -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -ffile-prefix-map=/var/folders/zt/kczk0t193tv6pgfnq32lz1vh0000gn/T/go-build202136550=/tmp/go-build -gno-record-gcc-switches -fno-common'

### Expected output

Calling GetByName on most resources with a name that has more than 1 space in it works.

### Actual output

 [ERROR] getting app connector group failed: FAILED: GET, https://config.private.zscaler.com/mgmtconfig/v1/admin/customers/1234/appConnectorGroup?page=1&pagesize=500&search=my%2Btest%2Bgroup%2B2, 400, 400 Bad Request, {
  "params" : [ "test" ],
  "id" : "filtering.input.invalid.operand",
  "reason" : "Invalid operand:test in Filtering criteria."
}

### Code demonstrating the issue

```
package main

import (
	"github.com/zscaler/zscaler-sdk-go/v2/zpa"
	"github.com/zscaler/zscaler-sdk-go/v2/zpa/services/appconnectorgroup"
	"github.com/zscaler/zscaler-sdk-go/v2/zpa/services/segmentgroup"
	"log"
)

func main() {
	zpaClient := zpa.NewClient(nil)
	appConnectorGroupService := appconnectorgroup.New(zpaClient)
	segmentGroupService := segmentgroup.New(zpaClient)
	group, _, err := appConnectorGroupService.GetByName("my test group")
	if err != nil {
		log.Printf("[ERROR] getting app connector group failed: %v\n", err)
	} else {
		log.Printf("[INFO] app connector group: %v\n", group)
	}

	segmentGroup, _, err := segmentGroupService.GetByName("my test group")
	if err != nil {
		log.Printf("[ERROR] getting segment group failed: %v\n", err)
	} else {
		log.Printf("[INFO] segment group: %v\n", segmentGroup)
	}
}
```

### Steps to reproduce

Run the provided code. It doesn't matter if the groups actually exist or not. If the group doesn't exist it should return an error about no matching group found, however, it instead returns an error from the API endpoint.

If the name of the resource contains more than 1 space (> 2 terms) then the API will now return a failure. 
This was introduced as part of the recent microtenant changes which switched most GetByName requests to send the name in the Search query instead of collecting all results and filtering locally. That was a nice optimization, however, the Zscaler API is treating the query as a set of operators if there are more than 2 terms in the search query parameter.

I would recommend updating all GetByName methods to use something like `Search: "name LIKE " + nameArgument`.

**Comment by willguibr** [comment]
Hi @bpedman Thanks for brining up this issue. This occurred in the last few days, due to potential API changes in the search mechanism where the search string should be formatted using `&`.
To fix the problem we have to ensure that the spaces are filled with "&" so that the API understands that as a valid search.
I've created the PR #170 for it and will push a new release in the next few days (Most likely next week).
Thank you
William
