### ISSUE TITLE
Failed to create vpn credentials, error: invalid character 'S' looking for beginning of value

### ISSUE THREAD

**Issue by gauravv9** [zscaler/zscaler-sdk-go#248]
### Confirmation

- [X] My issue isn't already found on the issue tracker.
- [X] I have replicated my issue using the latest version of the library and it is still present.

### zscaler-sdk-go version

2.5.0

### Go environment

NA

### Expected output

Expected the vpn credential to be created

### Actual output

 Getting an error when creating vpn credentials using zia Create API
" invalid character 'S' looking for beginning of value "

### Code demonstrating the issue

`configuredVpnCreds, _, err := service.Create(ziaVpnCreds)
	if err != nil {
		return nil, err
	}`

### Steps to reproduce

Kept the server running for a while that is responsible for making Zscaler requests via zscaler-sdk
Upon restarting the server, the request go through just fine.

**Comment by willguibr** [comment]
@gauravv9 Please share the configuration for analysis or open a support case with [Zscaler support](https://help.zscaler.com/zpa-submit-ticket) and ask for an escalation.
We can't provide you an answer without debug logs or the actual configuration itself.

**Comment by gauravv9** [comment]
```
 {
    "type": "UFQDN",
    "fqdn": "test07-vpn@dev-arista.com",
    "comments":"Test purpose only",
    "preSharedKey":"xyz"
  }
```
This is the configuration that was applied and on restarting the server it succeeded.

**Comment by gauravv9** [comment]
Seems to be getting SESSION_NOT_VALID as a response.
```msg="Zia: create vpn failed: (invalid character 'S' looking for beginning of value) for ({0 UFQDN test14-vpn@dev-arista.com  Arista123!  0xc000d0cd80 <nil>})" file="vpncredentials/vpncredentials.go:116"
2024-05-16 22:09:05.593	
msg="Zia: unmarshal error: (invalid character 'S' looking for beginning of value): ([83 69 83 83 73 79 78 95 78 79 84 95 86 65 76 73 68])" file="zia/client.go:160"```
Please correct me if I misunderstood, the session is refreshed in GenericRequest isn't it?

**Comment by willguibr** [comment]
@gauravv9 
Please download the latest version of the SDK ZIA package v2.61.2, which contains a fix regarding session refresh, and let us know if it fixed the problem you've reported.
Thanks.
Zscaler DevRel

**Comment by willguibr** [comment]
@gauravv9 Please share the GO program code you're using containing the client instantiation for further testing.
Thanks
