### ISSUE TITLE
GetAllByType return "appConnectorGroup" = nil instead the values 

### ISSUE THREAD

**Issue by chenmal** [zscaler/zscaler-sdk-go#255]
### Confirmation

- [X] My issue isn't already found on the issue tracker.
- [X] I have replicated my issue using the latest version of the library and it is still present.

### zscaler-sdk-go version

v2.5.23 - latest 

### Go environment

1.22

### Expected output

The func GetAllByType called with the parameter "GLOBAL_POLICY" should return also the "appConnectorGroup" of the relevant policies rules.
( (service *Service) GetAllByType(policyType string) ([]PolicyRuleResource, *http.Response, error) )

### Actual output

The field "appConnectorGroups" of policy rule that actually contains appp connector groups is null.

<img width="1075" alt="image" src="https://github.com/zscaler/zscaler-sdk-go/assets/61950280/1410133d-4e0d-4653-b147-b5f27a9f7947">

### Code demonstrating the issue

`zc.PolicyServiceV2.GetAllByType("GLOBAL_POLICY")`

The actual http call, called from GetAllByType.
GET https://config.zpabeta.net/mgmtconfig/v1/admin/customers/<number>/policySet/rules/policyType/GLOBAL_POLICY

response: 

```
[...
    {
      "id": "***",
      "name": "app connector server group conditions",
      "action": "ALLOW",
      "creationTime": "1717657044",
      "modifiedBy": "****",
      "modifiedTime": "1717657044",
      "operator": "AND",
      "policyType": "1",
      "priority": "1",
      "ruleOrder": "27",
      "conditions": [
        {
          "id": "1418023",
          "creationTime": "1717657044",
          "modifiedBy": "***",
          "modifiedTime": "1717657044",
          "negated": false,
          "operator": "OR",
          "operands": [
            {
              "id": "1418024",
              "creationTime": "1717657044",
              "modifiedBy": "***",
              "modifiedTime": "1717657044",
              "objectType": "CLIENT_TYPE",
              "lhs": "id",
              "rhs": "zpn_client_type_ip_anchoring"
            },
            {
              "id": "1418025",
              "creationTime": "1717657044",
              "modifiedBy": "***",
              "modifiedTime": "1717657044",
              "objectType": "CLIENT_TYPE",
              "lhs": "id",
              "rhs": "zpn_client_type_machine_tunnel"
            }
          ]
        }
      ],
      "appServerGroups": [
        {
          "id": "72059024262037506",
          "name": "Server Group"
        },
        {
          "id": "72059024262038023",
          "name": "Sarit1Server Group"
        }
      ],
      "privilegedCapabilities": {
        "id": ""
      }
    }
...]
```

The data is missing in the response , so it missing also in PolicyRuleResource return from the function.

**UI Http call:**
Request URL:
https://api.zpabeta.net/zpn/api/v1/admin/customers/<number>/policySet/rules/policyType/GLOBAL_POLICY/?scopeId=0&page=1&pagesize=100
Request Method:
GET

**UI http response:**
assistantGroups contains the values of appConnectorGroups

```
{
            "id": "72059024262038192",
            "modifiedTime": "1717657044",
            "creationTime": "1717657044",
            "modifiedBy": "***",
            "name": "app connector server group conditions",
            "ruleOrder": "27",
            "priority": "1",
            "policyType": "1",
            "operator": "AND",
            "conditions": [
                {
                    "id": "1418023",
                    "modifiedTime": "1717657044",
                    "creationTime": "1717657044",
                    "modifiedBy": "***",
                    "operator": "OR",
                    "negated": false,
                    "operands": [
                        {
                            "id": "1418024",
                            "modifiedTime": "1717657044",
                            "creationTime": "1717657044",
                            "modifiedBy": "***",
                            "objectType": "CLIENT_TYPE",
                            "lhs": "id",
                            "rhs": "zpn_client_type_ip_anchoring",
                            "name": "zpn_client_type_ip_anchoring"
                        },
                        {
                            "id": "1418025",
                            "modifiedTime": "1717657044",
                            "creationTime": "1717657044",
                            "modifiedBy": "***",
                            "objectType": "CLIENT_TYPE",
                            "lhs": "id",
                            "rhs": "zpn_client_type_machine_tunnel",
                            "name": "zpn_client_type_machine_tunnel"
                        }
                    ]
                }
            ],
            "action": "ALLOW",
            "disabled": "0",
            "appServerGroups": [
                {
                    "id": "72059024262037506",
                    "modifiedTime": "1696620196",
                    "creationTime": "1696545576",
                    "modifiedBy": "***",
                    "name": "Server Group",
                    "enabled": true,
                    "learningEnabled": true,
                    "configSpace": "DEFAULT"
                },
                {
                    "id": "72059024262038023",
                    "modifiedTime": "1714472974",
                    "creationTime": "1714472974",
                    "modifiedBy": "***",
                    "name": "Sarit1Server Group",
                    "enabled": true,
                    "learningEnabled": true,
                    "description": "test",
                    "configSpace": "DEFAULT"
                }
            ],
            "assistantGroups": [
                {
                    "id": "72059024262037540",
                    "modifiedTime": "1696608098",
                    "creationTime": "1696608098",
                    "modifiedBy": "***",
                    "name": "First App Connector Group",
                    "enabled": true,
                    "versionProfileId": "0",
                    "overrideVersionProfile": false,
                    "location": "Boulder, CO, USA",
                    "dnsQueryType": "IPV4_IPV6",
                    "cityCountry": "Boulder, US",
                    "countryCode": "US",
                    "tcpQuickAckApp": false,
                    "tcpQuickAckAssistant": false,
                    "tcpQuickAckReadAssistant": false,
                    "praEnabled": false,
                    "useInDrMode": false,
                    "wafDisabled": false,
                    "siemAssistantGroup": false
                },
                {
                    "id": "72059024262037963",
                    "modifiedTime": "1713095542",
                    "creationTime": "1713095542",
                    "modifiedBy": "***",
                    "name": "app connector group 1",
                    "enabled": true,
                    "versionProfileId": "0",
                    "overrideVersionProfile": false,
                    "location": "Israel",
                    "dnsQueryType": "IPV4_IPV6",
                    "cityCountry": "בית רימון, IL",
                    "countryCode": "IL",
                    "tcpQuickAckApp": false,
                    "tcpQuickAckAssistant": false,
                    "tcpQuickAckReadAssistant": false,
                    "praEnabled": false,
                    "useInDrMode": false,
                    "wafDisabled": false,
                    "siemAssistantGroup": false
                }
            ],
            "defaultRule": false,
            "restrictedEntity": false
        }```

### Steps to reproduce

1.Add Access Policy
2.Choose "App Connector Selection Method" -> "Specific App Connector groups or Server groups for the application
.."
3.Choose "App Connector Groups" -> few values 
4. Use the latest version of the sdk - policysetcontrollerv2 -> zc.PolicyServiceV2.GetAllByType("GLOBAL_POLICY")
5. Search for the new policy rule -> get the  PolicyRuleResource ->AppConnectorGroups value

The result is nil instead the app connector groups    


### References

No

**Comment by willguibr** [comment]
@chenmal 
You have not shared the code you are using for this test. Please share relevant parts of your code and we will investigate further.
Also, please set the following environment variables before executing your code, in order to capture the debug logs with the request and response.
```sh
export ZSCALER_SDK_LOG=true
export ZSCALER_SDK_VERBOSE=true
```

In our tests we do not see such issue based on the simple script and the output below.
**Script:**
```go
func main() {
	policyType := "GLOBAL_POLICY"

	client, err := tests.NewZpaClient()
	if err != nil {
		log.Fatalf("Error creating client: %v", err)
	}

	service := policysetcontrollerv2.New(client)

	policies, _, err := service.GetAllByType(policyType)
	if err != nil {
		log.Fatalf("Error retrieving policies: %v", err)
	}

	fmt.Printf("Retrieved %d policies of type %s:\n", len(policies), policyType)
	for _, policy := range policies {
		fmt.Printf("ID: %s, Name: %s\n", policy.ID, policy.Name)
	}
}
```

**Output:**
```json
{"totalPages":"1","totalCount":"0","list":[{"id":"72059124120061469","modifiedTime":"1717693640","creationTime":"1717693640","modifiedBy":"72059124120027137","name":"Example100","description":"Example100","ruleOrder":"1","priority":"2","policyType":"1","operator":"AND","action":"ALLOW","disabled":"0","defaultRule":false,"appConnectorGroups":[{"id":"72059124120050866","modifiedTime":"1714967837","creationTime":"1714967837","modifiedBy":"72059124120027170","name":"test_zpa_app_connector_group_FT5aY","enabled":true,"description":"test_zpa_app_connector_group_FT5aY","versionProfileId":"0","overrideVersionProfile":true,"location":"San Jose, CA, USA","dnsQueryType":"IPV4_IPV6","cityCountry":"San Jose, US","countryCode":"US","tcpQuickAckApp":true,"tcpQuickAckAssistant":true,"tcpQuickAckReadAssistant":true,"praEnabled":true,"useInDrMode":true,"wafDisabled":false,"lssAppConnectorGroup":false}]},{"id":"72059124120061470","modifiedTime":"1717693649","creationTime":"1717693649","modifiedBy":"72059124120027137","name":"Example200","description":"Example200","ruleOrder":"2","priority":"1","policyType":"1","operator":"AND","action":"ALLOW","disabled":"0","defaultRule":false,"appConnectorGroups":[{"id":"72059124120050866","modifiedTime":"1714967837","creationTime":"1714967837","modifiedBy":"72059124120027170","name":"test_zpa_app_connector_group_FT5aY","enabled":true,"description":"test_zpa_app_connector_group_FT5aY","versionProfileId":"0","overrideVersionProfile":true,"location":"San Jose, CA, USA","dnsQueryType":"IPV4_IPV6","cityCountry":"San Jose, US","countryCode":"US","tcpQuickAckApp":true,"tcpQuickAckAssistant":true,"tcpQuickAckReadAssistant":true,"praEnabled":true,"useInDrMode":true,"wafDisabled":false,"lssAppConnectorGroup":false}]}]}{"totalPages":"1","totalCount":"0","list":[{"id":"72059124120061469","modifiedTime":"1717693640","creationTime":"1717693640","modifiedBy":"72059124120027137","name":"Example100","description":"Example100","ruleOrder":"1","priority":"2","policyType":"1","operator":"AND","action":"ALLOW","disabled":"0","defaultRule":false,"appConnectorGroups":[{"id":"72059124120050866","modifiedTime":"1714967837","creationTime":"1714967837","modifiedBy":"72059124120027170","name":"test_zpa_app_connector_group_FT5aY","enabled":true,"description":"test_zpa_app_connector_group_FT5aY","versionProfileId":"0","overrideVersionProfile":true,"location":"San Jose, CA, USA","dnsQueryType":"IPV4_IPV6","cityCountry":"San Jose, US","countryCode":"US","tcpQuickAckApp":true,"tcpQuickAckAssistant":true,"tcpQuickAckReadAssistant":true,"praEnabled":true,"useInDrMode":true,"wafDisabled":false,"lssAppConnectorGroup":false}]},{"id":"72059124120061470","modifiedTime":"1717693649","creationTime":"1717693649","modifiedBy":"72059124120027137","name":"Example200","description":"Example200","ruleOrder":"2","priority":"1","policyType":"1","operator":"AND","action":"ALLOW","disabled":"0","defaultRule":false,"appConnectorGroups":[{"id":"72059124120050866","modifiedTime":"1714967837","creationTime":"1714967837","modifiedBy":"72059124120027170","name":"test_zpa_app_connector_group_FT5aY","enabled":true,"description":"test_zpa_app_connector_group_FT5aY","versionProfileId":"0","overrideVersionProfile":true,"location":"San Jose, CA, USA","dnsQueryType":"IPV4_IPV6","cityCountry":"San Jose, US","countryCode":"US","tcpQuickAckApp":true,"tcpQuickAckAssistant":true,"tcpQuickAckReadAssistant":true,"praEnabled":true,"useInDrMode":true,"wafDisabled":false,"lssAppConnectorGroup":false}]}]}
```

**Comment by chenmal** [comment]
The "policies" output you display is not in "PolicyRuleResource" -> "AppConnectorGroups" (The structure I see contains only id and name). 

Can you show me the implementation of the function you used? I used this function from policysetconttollerv2



func (service *Service) GetAllByType(policyType string) ([]PolicyRuleResource, *http.Response, error) {
	relativeURL := fmt.Sprintf(mgmtConfigV1+service.Client.Config.CustomerID+"/policySet/rules/policyType/%s", policyType)
	list, resp, err := common.GetAllPagesGenericWithCustomFilters[PolicyRuleResource](service.Client, relativeURL, common.Filter{MicroTenantID: service.microTenantID})
	if err != nil {
		return nil, nil, err
	}
	return list, resp, nil
}


type PolicyRuleResource struct {
	ID                       string                         `json:"id,omitempty"`
	Name                     string                         `json:"name,omitempty"`
	Description              string                         `json:"description,omitempty"`
	Action                   string                         `json:"action,omitempty"`
	ActionID                 string                         `json:"actionId,omitempty"`
	CreationTime             string                         `json:"creationTime,omitempty"`
	ModifiedBy               string                         `json:"modifiedBy,omitempty"`
	ModifiedTime             string                         `json:"modifiedTime,omitempty"`
	AuditMessage             string                         `json:"auditMessage,omitempty"`
	CustomMsg                string                         `json:"customMsg,omitempty"`
	Operator                 string                         `json:"operator,omitempty"`
	PolicySetID              string                         `json:"policySetId,omitempty"`
	PolicyType               string                         `json:"policyType,omitempty"`
	Priority                 string                         `json:"priority,omitempty"`
	ReauthIdleTimeout        string                         `json:"reauthIdleTimeout,omitempty"`
	ReauthTimeout            string                         `json:"reauthTimeout,omitempty"`
	RuleOrder                string                         `json:"ruleOrder,omitempty"`
	ZpnCbiProfileID          string                         `json:"zpnCbiProfileId,omitempty"`
	ZpnIsolationProfileID    string                         `json:"zpnIsolationProfileId,omitempty"`
	ZpnInspectionProfileID   string                         `json:"zpnInspectionProfileId,omitempty"`
	ZpnInspectionProfileName string                         `json:"zpnInspectionProfileName,omitempty"`
	MicroTenantID            string                         `json:"microtenantId,omitempty"`
	MicroTenantName          string                         `json:"microtenantName,omitempty"`
	Conditions               []PolicyRuleResourceConditions `json:"conditions,omitempty"`
	AppConnectorGroups       []AppConnectorGroups           `json:"connectorGroups,omitempty"`
	AppServerGroups          []AppServerGroups              `json:"appServerGroups,omitempty"`
	ServiceEdgeGroups        []ServiceEdgeGroups            `json:"serviceEdgeGroups,omitempty"`
	Credential               *Credential                    `json:"credential,omitempty"`
	PrivilegedCapabilities   PrivilegedCapabilities         `json:"privilegedCapabilities,omitempty"`
}



type AppConnectorGroups struct {
	ID   string `json:"id,omitempty"`
	Name string `json:"name,omitempty"`
}

**Comment by chenmal** [comment]
The issue is :

In GetAllByType PolicyRuleResource is the return value of the policies list, 

list, resp, err := common.GetAllPagesGenericWithCustomFilters[**PolicyRuleResource**](service.Client, relativeURL, common.Filter{MicroTenantID: service.microTenantID})...

in the json response - the data of app connector group key is "appConnectorGroups" , and the PolicyRuleResource-> AppConnectorGroups json key is : connectorGroups
`AppConnectorGroups       []AppConnectorGroups           `json:"connectorGroups,omitempty"``

So PolicyRuleResource->AppConnectorGroups return as null.

**Comment by chenmal** [comment]
Another issue : when using `func (service *Service) UpdateRule(policySetID, ruleId string, policySetRule *PolicyRule) (*http.Response, error) ` and sending as param policysetcontrollerv2.PolicyRule with app connector group, it not updated. 


The ignorance from app connector group (and server group) happen also in ConvertV1ResponseToV2Request.

**Comment by chenmal** [comment]
Hi, thanks for your answer.

The issue I am dealing with is related to the policySetControllerV2's functions. When using the policyRule and policyRuleResource objects provided in this controller, the appConnectorGroup value is not populated in policyRule and policyRuleResource.

(Ignore the value if it is part of the request, and do not return it as part of the response.)

I found the reason: it is because the response of the HTTP call returns the value under the json key "appConnectorGroups", but the objects in policySetControllerV2 are defined like this:
`AppConnectorGroups []AppConnectorGroups `json:"connectorGroups,omitempty"``

So, when I use functions like GetAllByType, the HTTP call response correctly returns the "appConnectorGroups" value, but when converting the response to the object, it ignores the "appConnectorGroups" value because it does not match the JSON key of any field in the object.

If the field were defined like this:

`AppConnectorGroups []AppConnectorGroups `json:"appConnectorGroups,omitempty"``
it would work correctly.

**Comment by chenmal** [comment]
Its seems that it solve the issue partially, 
If you will update a PolicyRule, and delete all the AppConnectorGroups/AppServerGroups/ServiceEdgeGroups/Conditions,
The update action will not update those fields, it will happen because the fields are tagged as "omitempty", and when we will pass empty slice as parameter, the Encode action (encode the object to json body) will ignore those fields and those fields will not be updated.
@willguibr 


`func (client *Client) getRequest(method, urlPath string, options, body interface{}) (*http.Request, error) {
	var buf io.ReadWriter
	if body != nil {
		buf = new(bytes.Buffer)
		err := json.NewEncoder(buf).Encode(body)
		if err != nil {
			return nil, err
		}
	}
	.....
	`

	AppConnectorGroups       []AppConnectorGroups           `json:"appConnectorGroups,omitempty"`
	AppServerGroups          []AppServerGroups              `json:"appServerGroups,omitempty"`
	ServiceEdgeGroups        []ServiceEdgeGroups            `json:"serviceEdgeGroups,omitempty"`
	Conditions               []PolicyRuleResourceConditions `json:"conditions,omitempty"`

**Comment by willguibr** [comment]
@chenmal Please check version 2.61.5 and let us know if it addresses the issue you're stating.
Regards
